"""Tests for the AI Code Validator mode: prompt builder + auto-detection."""

from app.agents.prompts import (
    AI_GENERATED_APPENDIX,
    build_review_prompt,
    detect_ai_generated,
)

# ── detect_ai_generated ─────────────────────────────────────────────────────


def test_detect_ai_generated_copilot() -> None:
    assert detect_ai_generated("Add caching", "Wrote this with GitHub Copilot.")


def test_detect_ai_generated_chatgpt_in_title() -> None:
    assert detect_ai_generated("ChatGPT: refactor auth flow", "")


def test_detect_ai_generated_ai_assisted_phrase() -> None:
    assert detect_ai_generated("feat: new endpoint", "AI-assisted implementation")


def test_detect_ai_generated_claude() -> None:
    assert detect_ai_generated("", "Drafted by Claude, reviewed manually.")


def test_detect_ai_generated_case_insensitive() -> None:
    assert detect_ai_generated("", "GENERATED BY AI — please review")


def test_detect_ai_generated_negative() -> None:
    assert not detect_ai_generated("Fix race in scheduler", "Manually triaged; see #421.")


def test_detect_ai_generated_empty_inputs() -> None:
    assert not detect_ai_generated("", "")
    assert not detect_ai_generated(None, None)  # type: ignore[arg-type]


# ── build_review_prompt ─────────────────────────────────────────────────────


def test_build_review_prompt_default_has_no_ai_banner() -> None:
    out = build_review_prompt(
        code="x = 1",
        language="python",
        ast_summary="trivial",
    )
    assert AI_GENERATED_APPENDIX.strip() not in out
    assert "AI-GENERATED" not in out


def test_build_review_prompt_ai_generated_adds_banner_first() -> None:
    out = build_review_prompt(
        code="x = 1",
        language="python",
        ast_summary="trivial",
        ai_generated=True,
    )
    # Banner must come before the code section so attention is biased from the start
    banner_idx = out.index("AI-GENERATED CODE MODE")
    code_idx = out.index("Full File")
    assert banner_idx < code_idx


def test_build_review_prompt_ai_generated_with_pr_context() -> None:
    out = build_review_prompt(
        code="x = 1",
        language="python",
        ast_summary="trivial",
        pr_context={"title": "feat: add caching", "body": "Copilot-assisted"},
        ai_generated=True,
    )
    assert "AI-GENERATED" in out
    assert "feat: add caching" in out
